services:
  mongodb:
    image: 'mongo:latest'
    container_name: mongo-db-gestao
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data
#  java-api:
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    container_name: java-api-pizzaria
#    links:
#      - mongo-db
